version: '3.8'

services:
  ui_node:
    build:
      context: ./UserInterface
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      # - nosql
      - sql
      - fastapi_yolo
      - fastapi_gps
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_yolo:
    build:
      context: ./FASTAPI_YOLO_IMAGE
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_yolo_trt:
    build:
      context: ./FASTAPI_YOLO_IMAGE_TENSORRT
      dockerfile: Dockerfile
    ports:
      - "8120:8120"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_vegetacao:
    build:
      context: ./FASTAPI_VEGETACAO
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]   
  fastapi_yolo_truck:
    build:
      context: ./FASTAPI_YOLO_IMAGE_TRUCK
      dockerfile: Dockerfile
    ports:
      - "8220:8220"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_yolo_pavimento:
    build:
      context: ./FASTAPI_YOLO_PAVIMENTO
      dockerfile: Dockerfile
    ports:
      - "8310:8310"
  fastapi_gps:
    build:
      context: ./FASTAPI_GPS_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_trecho:
    build:
      context: ./FASTAPI_TRECHO_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    depends_on:
      # - nosql
      - sql
  fastapi_init_new_trip:
    build:
      context: ./
      dockerfile: FASTAPI_GET_NEW_TRECHO/Dockerfile
    ports:
      - "8013:8013"
    depends_on:
      # - nosql
      - sql
  fastapi_numeric_ocr:
    build:
      context: ./FASTAPI_NUMERIC_OCR
      dockerfile: Dockerfile
    ports:
      - "8014:8014"
    depends_on:
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_classify_km_plates:
    build:
      context: ./FASTAPI_CLASSIFY_KM_PLATES
      dockerfile: Dockerfile
    ports:
      - "8015:8015"
    depends_on:
      - sql
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  fastapi_canteiro:
    build:
      context: ./FASTAPI_CANTEIRO_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8017:8017"
    depends_on:
      # - nosql
      - sql
  fastapi_bridge:
    build:
      context: ./FASTAPI_BRIDGE_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8018:8018"
    depends_on:
      # - nosql
      - sql
  fastapi_prf:
    build:
      context: ./FASTAPI_PRF_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8019:8019"
    depends_on:
      # - nosql
      - sql
  # nosql:
  #   build:
  #     context: ./NoSQL
  #     dockerfile: Dockerfile
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  sql:
    build:
      context: ./SQL
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mongo-data:
  mysql-data:
# docker-compose up --build
