consumer_timeout = 43200000  # 12 horas em milissegundos
# Limite mínimo de espaço em disco
disk_free_limit.absolute = 50MB

# Permitir acesso do user 'guest' de fora
loopback_users.guest = false

# Habilitar importação de definições
management.load_definitions = /etc/rabbitmq/definitions.json