version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta do RabbitMQ
      - "15672:15672"  # Painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: rdt
      RABBITMQ_DEFAULT_PASS: 123456
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 3
  # ui_node:
  #   build:
  #     context: ./UserInterface
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     # - nosql
  #     - sql
  #     - fastapi_yolo
  #     - fastapi_gps
  #   deploy:
  #       resources:
  #         reservations:
  #           devices:
  #             - capabilities: [gpu]
  fastapi_sign_classification:
    build:
      context: ./FASTAPI_SIGN_CLASSIFICATION
      dockerfile: Dockerfile
    ports:
      - "8016:8016"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_yolo:
    build:
      context: ./FASTAPI_YOLO_IMAGE
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on: []
      # - nosql
      # - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  # fastapi_yolo_trt:
  #   build:
  #     context: ./FASTAPI_YOLO_IMAGE_TENSORRT
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8120:8120"
  #   depends_on:
  #     # - nosql
  #     - sql
  #   deploy:
  #       resources:
  #         reservations:
  #           devices:
  #             - capabilities: [gpu]
  fastapi_vegetacao:
    build:
      context: ./FASTAPI_VEGETACAO
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]   
  # fastapi_yolo_truck:
  #   build:
  #     context: ./FASTAPI_YOLO_IMAGE_TRUCK
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8220:8220"
  #   depends_on:
  #     # - nosql
  #     - sql
  #   deploy:
  #       resources:
  #         reservations:
  #           devices:
  #             - capabilities: [gpu]
  # fastapi_yolo_pavimento:
  #   build:
  #     context: ./FASTAPI_YOLO_PAVIMENTO
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8310:8310"
  fastapi_gps:
    build:
      context: ./FASTAPI_GPS_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_trecho:
    build:
      context: ./FASTAPI_TRECHO_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    depends_on:
      # - nosql
      - sql
  fastapi_init_new_trip:
    build:
      context: ./
      dockerfile: FASTAPI_GET_NEW_TRECHO/Dockerfile
    ports:
      - "8013:8013"
    depends_on:
      # - nosql
      - sql
  fastapi_numeric_ocr:
    build:
      context: ./FASTAPI_NUMERIC_OCR
      dockerfile: Dockerfile
    ports:
      - "8014:8014"
    depends_on:
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_classify_km_plates:
    build:
      context: ./FASTAPI_CLASSIFY_KM_PLATES
      dockerfile: Dockerfile
    ports:
      - "8015:8015"
    depends_on:
      - sql
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  fastapi_canteiro:
    build:
      context: ./FASTAPI_CANTEIRO_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8017:8017"
    depends_on:
      # - nosql
      - sql
  fastapi_bridge:
    build:
      context: ./FASTAPI_BRIDGE_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8018:8018"
    depends_on:
      # - nosql
      - sql
  fastapi_prf:
    build:
      context: ./FASTAPI_PRF_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8019:8019"
    depends_on:
      # - nosql
      - sql
  fastapi_ns:
    build:
      context: ./FASTAPI_NS_PREDICT
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      # - nosql
      - sql
  fastapi_defensa:
    build:
      context: ./FASTAPI_DEFENSA
      dockerfile: Dockerfile
    ports:
      - "8420:8420"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]

  fastapi_defensa_trt:
    build:
      context: ./FASTAPI_DEFENSA_TRT
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
    ipc: host  # Compartilha memória IPC entre processos
    shm_size: '2gb'  # Aumenta o tamanho do shared memory
    ulimits:
      memlock: -1  # Evita travamento de memória
      stack: 67108864  # Define um tamanho maior para a pilh

  fastapi_drenagem:
    build:
      context: ./FASTAPI_DRENAGEM
      dockerfile: Dockerfile
    ports:
      - "8421:8421"
    depends_on:
      # - nosql
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
  fastapi_highway_number:
    build:
      context: ./FASTAPI_GET_HIGHWAY_NUMBER
      dockerfile: Dockerfile
    ports:
      - "8021:8021"
    depends_on:
      # - nosql
      - sql
  
  # fastapi_plot_coords_mato:
  #   build:
  #     context: ./FASTAPI_PLOT_COORDS_MATO
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8022:8022"
  #   depends_on:
  #     - sql
      
  fastapi_nearest_km:
   build:
     context: ./FASTAPI_KM_NEAREST
     dockerfile: Dockerfile
   ports:
     - "8023:8023"
   depends_on:
     - sql

  fastapi_horizontal_signage:
   build:
     context: ./FASTAPI_HORIZONTAL_SIGNAGE
     dockerfile: Dockerfile
   ports:
     - "8024:8024"
   depends_on:
     - sql

  fastapi_vegetacao_yolo:
    build:
      context: ./FASTAPI_VEGETACAO_YOLO
      dockerfile: Dockerfile
    ports:
      - "8400:8400"
    depends_on:
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]

  fastapi_vegetacao_yolo_cube:
    build:
      context: ./FASTAPI_VEGETACAO_YOLO_CUBE
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    depends_on:
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
    
  fastapi_qualidade:
    build:
      context: ./FASTAPI_QUALIDADE
      dockerfile: Dockerfile
    ports:
      - "8330:8330"
    depends_on:
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]

  drainage_api:
    build:
      context: ./FASTAPI_YOLO_DRAINAGE
      dockerfile: Dockerfile
    ports:
      - "8035:8035"
    depends_on:
      - sql
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]

  geometries:
    build:
      context: ./GEOMETRIES
      dockerfile: Dockerfile
  
    depends_on:
      - sql
  
  # nosql:
  #   build:
  #     context: ./NoSQL
  #     dockerfile: Dockerfile
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  sql:
    build:
      context: ./SQL
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  mongo-data:
  postgres-data:
# docker-compose up --build
