
services:

  sql_prod:
      build:
        context: ./SQL
        dockerfile: Dockerfile
      ports:
       - "${SQL_PORT:-5555}:5432"
      environment:
        POSTGRES_DB: ${DB_NAME:-mydatabase}
        POSTGRES_USER: ${DB_USER:-myuser}
        POSTGRES_PASSWORD: ${DB_PASS:-mypassword}
      volumes:
        - postgres-data-prod:/var/lib/postgresql/data

  geometries_prod:
    build:
      context: ./GEOMETRIES
      dockerfile: Dockerfile
  
    depends_on:
      - sql_prod
    
    environment:
      - HOST=sql_prod
    
volumes:
  postgres-data-prod: