database:
  url: "mysql://myuser:mypassword@192.168.18.15/mydatabase"
paths:
  root: "/mnt/HD12TB/DATASET_TESTE_RONDONOPOLIS/"
  relations_table: "relations_front.csv"
  images_dir: "images/"
inference:
  url: "http://127.0.0.1:8010/analyze/"
inference_gps:
  url: "http://127.0.0.1:8011/predict/"
api_get_cur_trip:
  url: "http://127.0.0.1:8013/latest/new-trip/"
viagem_id: 1