database:
  url: "mysql+mysqlconnector://myuser:mypassword@localhost/mydatabase"
paths:
  root: "/mnt/HD12TB/DATASET_TESTE_RONDONOPOLIS/"
  relations_table: "relations_front.csv"
  images_dir: "images/"
inference:
  url: "http://127.0.0.1:8010/analyze/"
inference_gps:
  url: "http://127.0.0.1:8011/predict/"
api_get_cur_trip:
  url: "http://127.0.0.1:8013/latest/new-trip/"
inference_defensa:
  url: "http://127.0.0.1:8420/latest/analyze/"
viagem_id: 1