database:
  url: "postgresql://myuser:mypassword@127.0.0.1:5433/mydatabase"
paths:
  root: "/mnt/HD12TB/DATASET_TESTE_RONDONOPOLIS/"
  relations_table: "relations_front.csv"
  images_dir: "images/"
inference:
  url: "http://127.0.0.1:8010/analyze/"
inference_gps:
  url: "http://127.0.0.1:8011/predict/"
api_get_cur_trip:
  url: "http://127.0.0.1:8013/latest/new-trip/"
inference_defensa:
  url: "http://127.0.0.1:8420/latest/analyze/"
inference_drenagem:
  url: "http://127.0.0.1:8421/latest/analyze/"
api_classify_blue_plate:
  url: "http://127.0.0.1:8015/v1_0/classify"
api_km_ocr:
  url: "http://127.0.0.1:8014/v1_0/ocr/get_km"
api_prf_predict:
  url: "http://127.0.0.1:8019/latest/prf-exists/"
  output: prf_near
api_km_nearest: 
  url: "http://127.0.0.1:8023/latest/get_segment_km/"
inference_vegetacao:
  url: "http://127.0.0.1:8300/analyze_4classes/"
  output: ['Score', 'Label', 'Classificação']
viagem_id: 1